server {
    listen 80;
    server_name localhost;

    # Разрешаем доступ к метрикам только локально (для экспортера)
    location /metrics {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        allow 10.17.86.172;
        deny all;
    }
}
